promoter/config/routes.rb
Rails.application.routes.draw do
  devise_for :bloggers
  root 'welcome#index'
  get 'blogpost/single' => "blogposts#single", as: 'single'
  get 'blogpost/blogger' => "blogposts#bloggerblogposts", as: 'bloggerblogposts'
  resources :blogposts
  resources :comments
 
end

promoter/app/models/blogger.rb
class Blogger < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :blogposts
end

promoter/app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
	has_many :comments
	belongs_to :blogger
end

promoter/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blogpost
end

promoter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

promoter/app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
before_action :authenticate_blogger!
helper_method :sort_column, :sort_direction


	def index
		@blogposts = Blogpost.order(sort_column + " " + sort_direction)
	end

	def single
    @blogpost = Blogpost.find(params[:id])
    @comments = @blogpost.comments.last(5)
  end



  	def new
  		if params[:blogpost] != nil
  		 @post =  Blogpost.new(:content => blogpost_params["content"], :title => blogpost_params["title"], :author => blogpost_params["author"], :blogger_id => blogpost_params["blogger_id"].to_i)
  	     if @post.save
           render action: "index"
       end
    end
    end


  private

  def blogpost_params
    params[:blogpost]
  end



  def sort_column
    Blogpost.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

promoter/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_blogger!


	  def create
      bid =params[:blogpost_id]
    @comment = Comment.new(comment_params)
    @comment.blogpost_id = bid
    @comment.save
    blogp = Blogpost.find(bid)

    respond_to do |format|
        format.json {render json: blogp.comments.last(5)}
        format.html {redirect_to request.referrer}
      end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content, :blogpost)
  end
end

promoter/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_action :authenticate_blogger!

end

promoter/app/helpers/application_helper.rb
require 'faker'
module ApplicationHelper

	def nav_link_to (name, url, style)
	if  request.fullpath == url
		return link_to "#{name}", url, :class => 'active', :style =>'background-color: #5cb85c;'
	else
		return link_to "#{name}".html_safe,  url, :style =>'color: #5cb85c;'

	end

	end

	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end


	def renderActionInOtherController(controller,action,params)
    c = controller.new
    c.params = params
    c.dispatch(action, request)
    c.response.body
	end


	def fakeMyData
		Blogpost.destroy_all

		50.times do 
			Blogpost.create(
				:title => Faker::Book.title,
				:author => Faker::Book.author,
				:content => Faker::Lorem.paragraph(20)
				)
				end
	end
end

promoter/app/views/blogposts/bloggerblogposts.html.erb
<h3> My Blogposts </h3>

	<table class='table'>
<tr>
  <th><%= sortable "title" %></th>
  <th></th>

</tr>
<% current_blogger.blogposts.each do |d| %>

<tr>
<td>
<%= link_to d.title,  single_path(:id => d.id)%>
</td>
<td><%= d.author %>
</td>
</tr>

<% end %>
</table>

promoter/app/views/blogposts/index.html.erb
<h2> All Blogposts </h2>

<table class='table'>
<tr>
  <th><%= sortable "title" %></th>
  <th><%= sortable "author" %></th>

</tr>
<% @blogposts.each do |d| %>

<tr>
<td>
<%= link_to d.title,  single_path(:id => d.id)%>
</td>
<td><%= d.author %>
</td>
</tr>

<% end %>
</table>

promoter/app/views/blogposts/new.html.erb
<h4> Create a Blogpost</h4>

<link href="https://cdn.quilljs.com/1.0.0-beta.0/quill.snow.css" rel="stylesheet">
BlogpostTitle<br>
<input id="atitle" type='text' name='title' placeholder="Title.."></input>

<%= quill_editor nil, { name: 'content', id: 'acontent'} %>

<br>
<button id="send" class='btn pull-right btn-success'>Promote blogpost</button>



<script>



$("#send").click(function(){

 var acontent = $('#acontent').val();
 var atitle = $('#atitle').val();
 var aauthor = "<%= current_blogger.email.to_s %>"
 var user = <%= current_blogger.id %>



$.ajax({
	type : 'get',
	url : '/blogposts/new',
	data :  {blogpost : {content: acontent, title: atitle, author: aauthor, blogger_id: user}}
})
window.location.replace("/blogpost/blogger");
});


$(document).ready(function() {
jQuery.fn.extend({



	    insertAtCursor: function(myValue, myValue2) {
	    	return this.each(function(i) {
			    if (document.selection) {
			      //For browsers like Internet Explorer
			      this.focus();
			      sel = document.selection.createRange();
			      sel.text = myValue;
			      this.focus();
			    }
			    else if (this.selectionStart || this.selectionStart == '0') {
			      //For browsers like Firefox and Webkit based
			      var startPos = this.selectionStart;
			      var endPos = this.selectionEnd;
			      var scrollTop = this.scrollTop;
			      this.value +=myValue + "" + myValue2 
                               
			      this.focus();
			      this.selectionStart = startPos + myValue.length;
			      this.selectionEnd = startPos + myValue.length;
			      this.scrollTop = scrollTop;

			    } else {
			      this.value += myValue;
			      this.focus();
			    }
		  	})
	    }
    
	})

})
var counter = 0;
      $(document).ready(function(){
            $("#acontent").keypress(function(e){
            	var cursor = $("#acontent").prop("selectionStart")
            	
                if (e.which == 2 && counter % 2 == 0) 
                {
                	console.log(counter)
                	counter ++;
                   $("#acontent").insertAtCursor("<b>", "</b>");
                }
                else if (e.which == 2 && counter % 2 == 1) 
                {
                	counter ++;
                	var SearchInput = $('#acontent');
					SearchInput.val(SearchInput.val());
					var strLength= SearchInput.val().length;
					SearchInput.focus();
					SearchInput[0].setSelectionRange(strLength, strLength);
                }

            });
        });






</script>

promoter/app/views/blogposts/single.html.erb
<h2><%= @blogpost.title %> </h2>

<%= @blogpost.content.html_safe %>

<hr>
<%= render 'layouts/comments' %>
<% @blogpost.comments.each do |c| %>
	<%= c.author %>
	<%= c.content %>
<% end %>
<%# render :text => renderActionInOtherController(CommentsController,:index,"params").html_safe %>

promoter/app/views/layouts/_comments.html.erb
<%  @presenter = {
      :comments => @comments,
      :form => {
        :action => comments_path,
        :csrf_param => request_forgery_protection_token,
        :csrf_token => form_authenticity_token,
        :blogpost_ident => "blogpost_id",
        :blogpost_id => @blogpost.id
      }
    }
    %>
<%= react_component('CommentBox', 
                    {:presenter => @presenter.to_json}, 
                    {:prerender => true}) %>

promoter/app/views/layouts/_navbar.html.erb
<nav class='nav navbar' style="">

	<ul class='nav navbar-nav'>

				<% if blogger_signed_in? %>
		  <li>
		  <%= link_to('Logout', destroy_blogger_session_path, :method => :delete) %>        
		  </li>
		<% else %>
		  <li>
		  <%= nav_link_to('Login', new_blogger_session_path, style: "color:#5cb85c;")  %>  
		  </li>		
		<% end %>

		<!-- nav_link_to : nav_link_to 'Grundlagen - Vertrauen', grundlagen_vertrauen_path, style: "color:black;" -->
		<li>
			<%= nav_link_to 'New Blogpost', new_blogpost_path, style: "color:#5cb85c;" %>
		</li>
			<li>
			<%= nav_link_to 'All Blogposts', blogposts_path, style: "color:#5cb85c;" %>
		</li>
	<li>
			<%= nav_link_to 'My Blogposts', bloggerblogposts_path, style: "color:#5cb85c;" %>
		</li>

	</ul>

</nav>

promoter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Promoter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
<h2><div id='rainbow'></div></h2>
<%= render 'layouts/navbar' %>
<%= yield %>
</div>
</body>

<script>
function rainbow(str){
  phase = 10000000000000;
  center = 128;
  width = 128;
  frequency = Math.PI*2/str.length;
  for (var i = 0; i < str.length; ++i)
  {
    var hexaStr = "0123456789ABCDEF";
    red   = Math.sin(frequency*i+2+phase) * width + center;
    green = Math.sin(frequency*i+0+phase) * width + center;
    blue  = Math.sin(frequency*i+4+phase) * width + center;
    $("#rainbow").append( '<font color="' + '#' +
      String(hexaStr.substr((red >> 4) & 0x0F,1)) + 
      hexaStr.substr(red & 0x0F,1) +
      String(hexaStr.substr((green >> 4) & 0x0F,1)) + 
      hexaStr.substr(green & 0x0F,1) + 
      String(hexaStr.substr((blue >> 4) & 0x0F,1)) + 
      hexaStr.substr(blue & 0x0F,1) + '">' + 
      str.substr(i,1) + '</font>');
  }
}
        
rainbow('Leightweight Blogger');
</script>
</html>

promoter/app/views/welcome/index.html.erb
<h2> Hello and welcome to the free Blogpost Promoter </h2>